DROP TABLE CATEGORY
CREATE TABLE CATEGORY (
    CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL
);

INSERT INTO CATEGORY (CATEGORY_NAME)
VALUES ('WHEELS');

INSERT INTO STORES (STORE_NAME)
VALUES('HMM'),
('HATTAN'),
('LEO');

-- Corrected version
INSERT INTO STORES (STORE_NAME, PHONE)
OUTPUT INSERTED.STORE_ID, INSERTED.STORE_NAME
VALUES
('STORE',  '00876'),
('STORE', '00314'),
('STORE',  '00676');


--SELECT
SELECT * FROM STORES;
SELECT* FROM CUSTOMERS;


INSERT INTO CUSTOMERS (CUSTOMER_ID, FNAME, LNAME, PHONE, EMAIL, CITY, ZIPCODE)
VALUES 
(1, 'Ali', 'Saeed', '00876', 'ali@email.com', 'MUSCAT', 12345),
(2, 'Salim', 'Hassan', '00314', 'salim@email.com', 'NIZWA', 23456),
(3, 'Zahra', 'Amal', '00676', 'zahra@email.com', 'QURUM', 34567);


UPDATE CUSTOMERS 
SET EMAIL = 'MOHAMMEDYK7@GMAIL.COM'
WHERE CUSTOMER_ID=3;