CREATE DATABASE SALESDB;
USE SALESDB;


CREATE TABLE SALESDB
(
 CUSTOMER_ID INT PRIMARY KEY,
 FNAME VARCHAR(15)NOT NULL,
 LNAME VARCHAR(15)NOT NULL,
 EMAIL VARCHAR(20)NOT NULL,
 PHONE VARCHAR(15) UNIQUE ,
 CITY VARCHAR(15),
 STREET VARCHAR(15),
 CONSTRAINT CUSTOMER_UQ UNIQUE (PHONE) ,
);

DROP TABLE IF EXISTS STORE;
GO
DROP TABLE IF EXISTS SALESDB;
GO


CREATE TABLE STORE(
STORE_ID INT PRIMARY KEY , 
STORE_NAME VARCHAR(30) , 
STORE_CITY VARCHAR(30) , 
PHONE VARCHAR(10) , 
);
ALTER TABLE STORE
ADD STREET VARCHAR(20);

ALTER TABLE STORE
ALTER COLUMN STORE_NAME VARCHAR(50);
alter table store
drop column  phone;

alter table STORE
add constraint STORE_NAME_uq unique (STORE_NAME);

CREATE TABLE BRANDS
(
BRAND_ID INT PRIMARY KEY ,
BRAND_NAME VARCHAR(20) ,
);

CREATE TABLE PRODUCTS 
(
PRODUCT_ID INT NOT NULL , 
PRODUCT_NAME VARCHAR(20) , 
MODEL INT , 
BRAND_ID INT );
ALTER TABLE PRODUCTS 
ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID);

DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
    BRAND_ID INT PRIMARY KEY,
    BRAND_NAME VARCHAR(20)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(20),
    MODEL INT,
    BRAND_ID INT,
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT BRANDS_PRODUCTS_FK FOREIGN KEY (BRAND_ID)
        REFERENCES BRANDS (BRAND_ID)
);

I HAD AN ERROR RUNNING THR FK OF BRANDS SO I JUST RECREATED THE CODES AGAIN (PRODUCTS, BRANDS ....) FOR REFRESHMENT 



DROP TABLE IF EXISTS STAFF;
GO
-- Create STAFF Table
CREATE TABLE STAFF (
    STAFF_ID INT PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    SALARY NUMERIC(8,2) CHECK (SALARY BETWEEN 3000 AND 15000),
    HIRE_DATE DATE,
    STORE_NO INT,
    CONSTRAINT STORE_STAFF_FK FOREIGN KEY (STORE_NO)
	REFERENCES STORE(STORE_ID)
);
GO

CREATE TABLE STORE_V2 (
    STORE_ID INT PRIMARY KEY,
    STORE_NAME VARCHAR(30),
    STORE_CITY VARCHAR(30),
    PHONE VARCHAR(10)
);
GO
DROP TABLE IF EXISTS STORE_V2;

---RENAME
EXEC SP_RENAME 'STAFF' , 'WORKERS';
EXEC SP_RENAME 'WORKERS.LNAME' , 'LASTNAME' , 'COLUMN';












